<a href="https://colab.research.google.com/github/shahina90728/Data-Science/blob/main/pgm1_to_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
array_from_list = np.array([1,2,3,4,5])
print("Array from list:",array_from_list)

array_with_range = np.arange(10)
print("Array with range:",array_with_range)

zeros_array = np.zeros((3,3))
print("Array of zeros:\n",zeros_array)

ones_array = np.ones((2,5))
print("Array of ones:\n",ones_array)


Array from list: [1 2 3 4 5]
Array with range: [0 1 2 3 4 5 6 7 8 9]
Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
add_result = np.add(a,b)
print("Addition result:",add_result)

sub_result = np.subtract(a,b)
print("Subtraction result:",sub_result)

mul_result = np.multiply(a,b)
print("Multiplication result:",mul_result)

div_result = np.divide(a,b)
print("Division result:",div_result)

Addition result: [5 7 9]
Subtraction result: [-3 -3 -3]
Multiplication result: [ 4 10 18]
Division result: [0.25 0.4  0.5 ]


In [8]:
array = np.arange(12)
print("Orginal Array:",array)
reshaped_array = np.reshape(array,(3,4))
print("Reshaped array:\n",reshaped_array)

reshaped_array_3d = np.reshape(array,(2,3,2))
print("Reshaped 3D array:\n",reshaped_array_3d)

Orginal Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped 3D array:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [9]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original 2D array:\n",array_2d)

element = array_2d[1,2]
print("Element at (1,2):",element)

subarray= array_2d[1:3,0:2]
print("sliced subarray:\n",subarray)

column = array_2d[:,1]
print("column 1:",column)


Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (1,2): 6
sliced subarray:
 [[4 5]
 [7 8]]
column 1: [2 5 8]


In [11]:
array =  np.array([1,2,3,4,5,6,7,8,9,10])
print("Original array:",array)

mean = np.mean(array)
print("Mean :",mean)

median = np.median(array)
print("Median:",median)

std_dev = np.std(array)
print("Standard Deviation:",std_dev)

min_val = np.min(array)
print("Minimum value:",min_val)

max_val = np.max(array)
print("Maximum value:",max_val)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Mean : 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Minimum value: 1
Maximum value: 10
